using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Glue.Web")]
[assembly: AssemblyTitleAttribute("Glue.Web")]
[assembly: AssemblyVersionAttribute("1.0.1075")]
[assembly: AssemblyInformationalVersionAttribute("1.0.1075")]
[assembly: ComVisibleAttribute(false)]

