using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Glue.Lib")]
[assembly: AssemblyTitleAttribute("Glue.Lib")]
[assembly: AssemblyVersionAttribute("2.0.1570")]
[assembly: AssemblyInformationalVersionAttribute("2.0.1570")]
[assembly: ComVisibleAttribute(false)]

