using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Glue")]
[assembly: AssemblyTitleAttribute("Glue.Data.PostgreSQL")]
[assembly: AssemblyCompanyAttribute("Glue Project, http://www.glueproject.com")]
[assembly: AssemblyCopyrightAttribute("Copyright Glue Project 2008")]
[assembly: AssemblyVersionAttribute("0.9.10")]
[assembly: AssemblyInformationalVersionAttribute("0.9.10")]

